![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

# Introduction to data manipulation and visualisation with Pandas

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

# Introduction

pandas is a library written for the Python for data manipulation and analysis. In particular, it offers data structures and operations for manipulating numerical tables and time series.

So since it's a module, we need to import it on our notebook

In [ ]:
# importing pandas
import pandas as pd

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Basic data exploration

- Reading data
- Selecting columns
- selecting rows

In [ ]:
# reading a .csv file with pandas
df = pd.read_csv('sample_data/california_housing_train.csv')

In [ ]:
type(df)
# pandas represents data in a tabular form known as DataFrame

pandas.core.frame.DataFrame

In [ ]:
# EXERCISE: display top 5 rows of dataframe

In [ ]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Selecting Columns
This is equivalent to "SELECT ..." statement in SQL

* Two ways
    - `df['col_name']` or `df[[array of cols]]`
    - `df.col_name` (auto complete feature works 🙂)

In [ ]:
# EXERCISE: select column total_bedrooms

In [ ]:
# each column of a dataframe is known as Series, you can read about it here
type(df['population'])

pandas.core.series.Series

### Till now we saw that pandas only work with 2 data structures
- DataFrame
- Series

In [ ]:
# EXERCISE: select the columns total_bedrooms, population and households

In [ ]:
# EXERCISE: find the number of rows and columns in this dataframe
# Hint: remember you can use the cheat sheet or ChatGPT!

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Some basic functions for data exploration

In [ ]:
# Exercise: select top 10, rows in the dataframe (by default head gives you top 5 rows)

In [ ]:
# Exercise: select last 10 rows of dataframe

In [ ]:
# EXERCISE: get array of all the column names in the dataframe

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Selecting Rows
* Main way is
    - `df.loc[]`

In [ ]:
# EXERCISE: select the 2nd row of the Dataframe, aka the row with index column = 2

In [ ]:
# .loc also takes the name of column or array of columns for showing the selective columns
# EXERCISE: find value of total_rooms for 2nd row in dataframe

In [ ]:
# EXERCISE: find value of both total_rooms and total_bedrooms for 2nd row in dataframe

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Conditional selection of rows

In [ ]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [ ]:
# EXERCISE: find rows where latitude value is equal smaller than 34

### multiple condition:
- & => and
- | => or
- ! => not

In [ ]:
# EXERCISE: select rows where 'total_bedrooms' is >400 and households is < 300

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Getting some insights of data

In [ ]:
# gives basic information about columns in dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

In [ ]:
# gives statistical information about columns of dataframe
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [ ]:
# EXERCISE: get type of each column in the dataframe

In [ ]:
# EXERCISE: show NUMBER of unique values for latitude

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Dropping Stuff
- Droping a column
- Droping a row
- Droping `nan` values (we have a particular section for treatment of `nan` values)

In [ ]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [ ]:
# EXERCISE: dropping entire `total_bedrooms` column from dataframe,
# remember to specify the correct axis!

In [ ]:
# EXERCISE: drop columns total_bedrooms and median_income

In [ ]:
# EXERCISE: drop rows 1 to 5
# Remember: axis=0 represents that now we are moving along rows and dropping the values

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Statistical insights from data

You've already seen the `describe` method, which gives you a good "summary" of the `DataFrame`. Let's explore other methods in more detail:

In [ ]:
# EXERCISE: get min and max of total_bedrooms

In [ ]:
# EXERCISE: print sum of columnn median_house_value

In [ ]:
# EXERCISE: print mean of column total_bedrooms

In [ ]:
# EXERCISE: apply describe function to a single column and see what happens

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

# The End !!


During the next session we will explore more Pandas functionalities like:

- matrix operations
- how to handle NULL values
- create some plots from a pandas dataframe

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)